version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Must be "true" at startup
      KAFKA_LOG_CLEANER_ENABLE: true
      # Make logs roll quickly
      KAFKA_LOG_SEGMENT_MS: 100
      # Tombstones older than 1s can be removed
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 100
      # If 10% of the segment is dirty, attempt compaction
      KAFKA_LOG_CLEANER_MIN_CLEANABLE_RATIO: 0.1
