# https://github.com/Ghersi75/SpringBootRefundProject1/blob/main/docker-compose.yml
# Taken from previous projects
version: '3.8'

services:
  database:
    image: postgres:16
    container_name: projec2-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./src/main/resources/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432" # Expose database for debugging


  backend:
    depends_on:
      - database
    image: maven:3.8.3-openjdk-17
    container_name: project2-backend
    working_dir: /app
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/db
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      # https://containers.fan/posts/speed-up-maven-docker-builds-with-cache
      # Create local maven cache of dependecies so it doesnt download each time docker container is removed and recreated
      - ./mvn-cache/:/root/.m2
    command: [ "sh", "-c", "mvn clean test && mvn clean spring-boot:run" ]
