# https://github.com/Ghersi75/SpringBootRefundProject1/blob/main/docker-compose.yml
# Taken from previous projects
version: '3.8'

services:
  db:
    image: postgres:16
    container_name: projec2-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./src/main/resources/initdb:/docker-entrypoint-initdb.d