# https://github.com/Ghersi75/SpringBootRefundProject1/blob/main/docker-compose.yml
# Taken from previous projects
# github version
# version: '3.8'

# services:
#   database:
#     image: postgres:16
#     container_name: projec2-db
#     environment:
#       POSTGRES_DB: db
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#     volumes:
#       - ./src/main/resources/initdb:/docker-entrypoint-initdb.d

#   backend:
#     depends_on:
#       - database
#     image: maven:3.8.3-openjdk-17
#     container_name: project2-backend
#     working_dir: /app
#     environment:
#       DATABASE_URL: jdbc:postgresql://database:5432/db
#       DATABASE_USERNAME: user
#       DATABASE_PASSWORD: password
#     ports:
#       - "8081:8081"
#     volumes:
#       - ./:/app
#       # https://containers.fan/posts/speed-up-maven-docker-builds-with-cache
#       # Create local maven cache of dependecies so it doesnt download each time docker container is removed and recreated
#       - ./mvn-cache/:/root/.m2
#     command: [ "sh", "-c", "mvn clean spring-boot:run" ]


#local version
# version: '3.8'

services:
  backend:
    depends_on:
      - kafka
    image: maven:3.8.3-openjdk-17
    container_name: project2-backend
    working_dir: /app
    environment:
      DATABASE_URL: jdbc:mysql://host.docker.internal:3306/game_forum
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      - ./mvn-cache/:/root/.m2
    command: [ "sh", "-c", "mvn clean spring-boot:run" ]

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093