# https://github.com/Ghersi75/SpringBootRefundProject1/blob/main/docker-compose.yml
# Taken from previous projects
version: '3.8'

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    # volumes:
    #   - ./src/main/resources/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432" # Expose database for debugging


  backend:
    depends_on:
      - database
      - kafka
    image: maven:3.8.3-openjdk-17
    container_name: project2-backend
    working_dir: /app
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/db
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      - ./mvn-cache/:/root/.m2
    command: [ "sh", "-c", "mvn clean spring-boot:run -Dspring-boot.run.profiles=docker-local" ]


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"


  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      
    ports:
      - "9092:9092"

