name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - jenkins-testing
    # Can only have paths or paths-ignore
    paths:
      # Only run when src/ folders are changed
      - "src/**"
      # Don't run if .github folder is the only thing changed
      # No point rebuilding a spring boot app if all thats changed is github workflow files
      - "!.github/**"

jobs:
  test_package_build:
    name: Maven Package and Docker Image
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/project2-backend:dev

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Run tests and build maven with production environment variables
        run: mvn clean package -Pprod
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        continue-on-error: false
      
      - name: Create updated image build
        run: |
          docker build . -t $DOCKER_REPO
          docker push $DOCKER_REPO
    
  docker_deploy:
    name: Docker Image CD
    runs-on: [self-hosted, backend]
    needs: test_package_build

    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/project2-backend:dev
    
    steps:
      - name: Pull docker image
        run: docker pull $DOCKER_REPO
      - name: Delete old docker container
        run: docker rm -f cicd-pipeline-container || true
      - name: Run docker container
        run: docker run -d -p 8081:8081 --name cicd-pipeline-container $DOCKER_REPO

