name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - jenkins-testing

jobs:
  test_and_package:
    name: Maven Package
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Run tests and build maven with production environment variables
        run: mvn clean package -Pprod
  
  docker_build_image:
    name: Docker Image CI
    runs-on: ubuntu-latest
    needs: test_and_package

    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/project2-backend:dev
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        continue-on-error: false
      
      - name: Create updated image build
        run: |
          docker build . -t $DOCKER_REPO
          docker push $DOCKER_REPO
    
  docker_deploy:
    name: Docker Image CD
    runs-on: [self-hosted, backend]
    needs: docker_build_image

    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/project2-backend:dev
    
    steps:
      - name: Pull docker image
        run: docker pull $DOCKER_REPO
      - name: Delete old docker container
        run: docker rm -f cicd-pipeline-container || true
      - name: Run docker container
        run: docker run -d -p 8081:8081 --name cicd-pipeline-container $DOCKER_REPO

