name: Docker Image CI

on:
  push:
    branches:
      - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/project2-backend:dev
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        continue-on-error: false
      
      - name: Create updated image build
        run: |
          docker build . -t $DOCKER_REPO
          docker push $DOCKER_REPO