name: Docker Image CD

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: [self-hosted, backend]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/project2-backend:dev
    
    steps:
      - name: Pull docker image
        run: docker pull $DOCKER_REPO
      - name: Delete old docker container
        run: docker rm -f cicd-pipeline-container || true
      - name: Run docker container
        run: docker run -d -p 8081:8081 --name cicd-pipeline-container $DOCKER_REPO
