name: Maven Package

on:
  push:
    branches: [jenkins-testing]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup maven
        uses: s4u/setup-maven-action@3.9.9

      - run: mvn clean package -Pprod