name: Maven Build

on:
  push:
    branches:
      - jenkins-testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Maven Installation
        run: mvn -v
      
      - name: Run Maven Build with Debug Logs
        run: mvn clean compile -Pprod -X
