name: Maven Build

on:
  push:
    branches:
      - jenkins-testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Install Maven
      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      # Run Maven commands
      - name: Run Maven Build
        run: mvn clean compile -Pprod -X
